BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.4

        TextInput:
            id: input_miles
            text: ''
            multiline: False
            font_size: 40

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.3

            Button:
                text: 'Up'
                on_press: app.handle_increment(input_miles.text, 1)

            Button:
                text: 'Down'
                on_press: app.handle_increment(input_miles.text, -1)

    Button:
        text: 'Convert miles to km'
        size_hint_y: 0.3
        on_press: app.handle_convert(input_miles.text)

    Label:
        text: app.result_text
        font_size: 48
        color: (1, 1, 0, 1)  # Yellow
        size_hint_y: 1.2
        canvas.before:
            Color:
                rgba: (0, 0, 0, 1)  # Black background
            Rectangle:
                pos: self.pos
                size: self.size
