BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input_number
            text: ''
            font_size: 48
            multiline: False

        Button:
            text: 'Square'
            on_press: app.handle_calculate(input_number.text)

        Label:
            id: output_label
            text: ''
            font_size: 48
            color: (1, 0.6, 0.6, 1)

    Label:
        text: 'Enter a number and press "Square"'
        font_size: 18
